/*
CREATE TABLE DATAPOWER.DP_MESSAGES
 (MESSAGE_ID   VARCHAR(100)     NOT NULL,
  MESSAGE  XML NOT NULL,
  MESSAGE_TYPE VARCHAR(3) NOT NULL,
  MESSAGE_DATE DATE NOT NULL,
  PRIMARY KEY(MESSAGE_ID));
  
  
  CREATE TABLE DATAPOWER.DP_ERRORMESSAGE
 (MESSAGE_ID   VARCHAR(100)     NOT NULL,
  MESSAGE  XML NOT NULL,
  MESSAGE_DATE DATE NOT NULL,
  PRIMARY KEY(MESSAGE_ID));


 CREATE TABLE DATAPOWER.DP_ERRORHANDLING
 (ERRORHANDLING_ID   INTEGER     NOT NULL,
  MESSAGE_ID  VARCHAR(100) NOT NULL,
  RETRY_ID	INTEGER NOT NULL,
  RETRY_ENDPOINT  VARCHAR(200) NOT NULL,
  RETRY_DATE DATE NOT NULL,
  STATUS VARCHAR(10),
  PRIMARY KEY(ERRORHANDLING_ID));

 CREATE TABLE DATAPOWER.DP_ERRORHANDLING_RETRYTYPES
 (RETRYTYPE_ID   INTEGER     NOT NULL,
  RETRY_COUNT   INTEGER     NOT NULL,
  RETRY_INTERVAL	INTEGER     NOT NULL,
  PRIMARY KEY(RETRYTYPE_ID));


insert into DP_ERRORHANDLING_RETRYTYPES values (1,3,60)
            
                                    
  
  
 */

--insert into dp_messages values ('1','<XML>HELLO</XML>',2,current timestamp)
--select * from DATAPOWER.DP_MESSAGES;

--xquery 
--for $y in db2-fn:xmlcolumn('DATAPOWER.DP_MESSAGES.MESSAGE')/*:Envelope/*:Header/*:messageID return $y/text()

xquery 
for $message in db2-fn:xmlcolumn('DATAPOWER.DP_MESSAGES.MESSAGE')/*:Envelope return $message






